# Site settings
title: "SANGITA KUMARI"
description: "This is my peronal webpage"
url: "https://Sangitakumari123github.io"  # Your GitHub Pages URL or custom domain
baseurl: ""  # Leave blank for root or use "/repository-name" for project site
author: 
  name: "SANGITA KUMARI"
  email: "sangeetakapil8@gmail.com"
  
# Build settings
theme: jekyll-theme-architect  # You can change this to any other theme available on GitHub Pages or custom theme
plugins:
  - jekyll-feed   # This adds RSS feed functionality
  
# Deployment settings
markdown: kramdown  # Markdown engine
highlighter: rouge  # Syntax highlighter
permalink: pretty   # Clean URLs without .html at the end
